Repository Stjoo0925/spring-repeat, pull requests merged in 2024-08, with the labels that each got.

#17 feat : entity, dto, repository
  src/main/java/com/test/springrepeat/user/entity/UserEntity.java
  src/main/java/com/test/springrepeat/user/model/UserDTO.java
  src/main/java/com/test/springrepeat/user/repository/UserRepository.java
Labels: In development

#20 feat : DTO,Entity,Repository
  src/main/java/com/test/springrepeat/order/dto/OrderDTO.java
  src/main/java/com/test/springrepeat/order/entity/Order.java
  src/main/java/com/test/springrepeat/order/repository/OrderRepository.java
Labels: In development

#21 fix : Order fixed
  src/main/java/com/test/springrepeat/order/entity/Order.java
Labels: fixed

#22 Repeat/order allview
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/dto/OrderDTO.java
  src/main/java/com/test/springrepeat/order/entity/Order.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
  src/main/java/com/test/springrepeat/user/entity/UserEntity.java
  src/main/java/com/test/springrepeat/user/model/UserDTO.java
Labels: Development completed

#23 feat : update entity
  src/main/java/com/test/springrepeat/user/entity/UserEntity.java
Labels: Development completed

#24 feat : update dto,controller,service
  src/main/java/com/test/springrepeat/user/controller/UserController.java
  src/main/java/com/test/springrepeat/user/model/UserDTO.java
  src/main/java/com/test/springrepeat/user/service/UserService.java
Labels: Development completed

#25 feat : update controller,service
  src/main/java/com/test/springrepeat/user/controller/UserController.java
  src/main/java/com/test/springrepeat/user/service/UserService.java
Labels: Development completed

#26 feat: order detail view
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/entity/Order.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
Labels: Development completed

#27 feat: order create
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/dto/OrderDTO.java
  src/main/java/com/test/springrepeat/order/entity/Order.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
Labels: Development completed

#29 feat: order update
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
  src/main/resources/application.yml
Labels: Development completed

#30 feat : update controller,service,yml,dto,entity,global
  src/main/java/com/test/springrepeat/ExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/test/springrepeat/user/controller/UserController.java
  src/main/java/com/test/springrepeat/user/entity/UserEntity.java
  src/main/java/com/test/springrepeat/user/model/UserDTO.java
  src/main/java/com/test/springrepeat/user/service/UserService.java
  src/main/resources/application.yml
Labels: Development completed

#32 feat : update controller,service
  src/main/java/com/test/springrepeat/user/controller/UserController.java
  src/main/java/com/test/springrepeat/user/service/UserService.java
Labels: Development completed

#34 feat: order delete
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
Labels: Development completed

#35 feat : update controller,service
  src/main/java/com/test/springrepeat/user/controller/UserController.java
  src/main/java/com/test/springrepeat/user/service/UserService.java
Labels: Development completed

#36 Repeat/order
  src/main/java/com/test/springrepeat/order/controller/OrderController.java
  src/main/java/com/test/springrepeat/order/dto/OrderDTO.java
  src/main/java/com/test/springrepeat/order/entity/Order.java
  src/main/java/com/test/springrepeat/order/service/OrderService.java
  src/main/java/com/test/springrepeat/user/entity/UserEntity.java
  src/main/java/com/test/springrepeat/user/model/UserDTO.java
  src/main/resources/application.yml
Labels: Development completed
